/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";
import type BN from "bn.js";
import type { EventEmitter } from "events";
import type { EventLog } from "web3-core";
import type { ContractOptions } from "web3-eth-contract";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Failure = ContractEventLog<{
  error: string;
  info: string;
  detail: string;
  0: string;
  1: string;
  2: string;
}>;
export type LiquidateNAI = ContractEventLog<{
  liquidator: string;
  borrower: string;
  repayAmount: string;
  nTokenCollateral: string;
  seizeTokens: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type MintFee = ContractEventLog<{
  minter: string;
  feeAmount: string;
  0: string;
  1: string;
}>;
export type MintNAI = ContractEventLog<{
  minter: string;
  mintNAIAmount: string;
  0: string;
  1: string;
}>;
export type NewComptroller = ContractEventLog<{
  oldComptroller: string;
  newComptroller: string;
  0: string;
  1: string;
}>;
export type NewTreasuryAddress = ContractEventLog<{
  oldTreasuryAddress: string;
  newTreasuryAddress: string;
  0: string;
  1: string;
}>;
export type NewTreasuryGuardian = ContractEventLog<{
  oldTreasuryGuardian: string;
  newTreasuryGuardian: string;
  0: string;
  1: string;
}>;
export type NewTreasuryPercent = ContractEventLog<{
  oldTreasuryPercent: string;
  newTreasuryPercent: string;
  0: string;
  1: string;
}>;
export type RepayNAI = ContractEventLog<{
  payer: string;
  borrower: string;
  repayNAIAmount: string;
  0: string;
  1: string;
  2: string;
}>;

export interface NaiUnitroller extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): NaiUnitroller;
  clone(): NaiUnitroller;
  methods: {
    _become(unitroller: string): NonPayableTransactionObject<void>;

    _setComptroller(comptroller_: string): NonPayableTransactionObject<string>;

    _setTreasuryData(
      newTreasuryGuardian: string,
      newTreasuryAddress: string,
      newTreasuryPercent: number | string | BN
    ): NonPayableTransactionObject<string>;

    admin(): NonPayableTransactionObject<string>;

    comptroller(): NonPayableTransactionObject<string>;

    getBlockNumber(): NonPayableTransactionObject<string>;

    getMintableNAI(minter: string): NonPayableTransactionObject<{
      0: string;
      1: string;
    }>;

    getNAIAddress(): NonPayableTransactionObject<string>;

    initialize(): NonPayableTransactionObject<void>;

    isNarwhalNAIInitialized(): NonPayableTransactionObject<boolean>;

    liquidateNAI(
      borrower: string,
      repayAmount: number | string | BN,
      nTokenCollateral: string
    ): NonPayableTransactionObject<{
      0: string;
      1: string;
    }>;

    mintNAI(
      mintNAIAmount: number | string | BN
    ): NonPayableTransactionObject<string>;

    naiControllerImplementation(): NonPayableTransactionObject<string>;

    narwhalInitialIndex(): NonPayableTransactionObject<string>;

    narwhalNAIMinterIndex(arg0: string): NonPayableTransactionObject<string>;

    narwhalNAIState(): NonPayableTransactionObject<{
      index: string;
      block: string;
      0: string;
      1: string;
    }>;

    pendingAdmin(): NonPayableTransactionObject<string>;

    pendingNAIControllerImplementation(): NonPayableTransactionObject<string>;

    repayNAI(
      repayNAIAmount: number | string | BN
    ): NonPayableTransactionObject<{
      0: string;
      1: string;
    }>;

    treasuryAddress(): NonPayableTransactionObject<string>;

    treasuryGuardian(): NonPayableTransactionObject<string>;

    treasuryPercent(): NonPayableTransactionObject<string>;
  };
  events: {
    Failure(cb?: Callback<Failure>): EventEmitter;
    Failure(options?: EventOptions, cb?: Callback<Failure>): EventEmitter;

    LiquidateNAI(cb?: Callback<LiquidateNAI>): EventEmitter;
    LiquidateNAI(
      options?: EventOptions,
      cb?: Callback<LiquidateNAI>
    ): EventEmitter;

    MintFee(cb?: Callback<MintFee>): EventEmitter;
    MintFee(options?: EventOptions, cb?: Callback<MintFee>): EventEmitter;

    MintNAI(cb?: Callback<MintNAI>): EventEmitter;
    MintNAI(options?: EventOptions, cb?: Callback<MintNAI>): EventEmitter;

    NewComptroller(cb?: Callback<NewComptroller>): EventEmitter;
    NewComptroller(
      options?: EventOptions,
      cb?: Callback<NewComptroller>
    ): EventEmitter;

    NewTreasuryAddress(cb?: Callback<NewTreasuryAddress>): EventEmitter;
    NewTreasuryAddress(
      options?: EventOptions,
      cb?: Callback<NewTreasuryAddress>
    ): EventEmitter;

    NewTreasuryGuardian(cb?: Callback<NewTreasuryGuardian>): EventEmitter;
    NewTreasuryGuardian(
      options?: EventOptions,
      cb?: Callback<NewTreasuryGuardian>
    ): EventEmitter;

    NewTreasuryPercent(cb?: Callback<NewTreasuryPercent>): EventEmitter;
    NewTreasuryPercent(
      options?: EventOptions,
      cb?: Callback<NewTreasuryPercent>
    ): EventEmitter;

    RepayNAI(cb?: Callback<RepayNAI>): EventEmitter;
    RepayNAI(options?: EventOptions, cb?: Callback<RepayNAI>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Failure", cb: Callback<Failure>): void;
  once(event: "Failure", options: EventOptions, cb: Callback<Failure>): void;

  once(event: "LiquidateNAI", cb: Callback<LiquidateNAI>): void;
  once(
    event: "LiquidateNAI",
    options: EventOptions,
    cb: Callback<LiquidateNAI>
  ): void;

  once(event: "MintFee", cb: Callback<MintFee>): void;
  once(event: "MintFee", options: EventOptions, cb: Callback<MintFee>): void;

  once(event: "MintNAI", cb: Callback<MintNAI>): void;
  once(event: "MintNAI", options: EventOptions, cb: Callback<MintNAI>): void;

  once(event: "NewComptroller", cb: Callback<NewComptroller>): void;
  once(
    event: "NewComptroller",
    options: EventOptions,
    cb: Callback<NewComptroller>
  ): void;

  once(event: "NewTreasuryAddress", cb: Callback<NewTreasuryAddress>): void;
  once(
    event: "NewTreasuryAddress",
    options: EventOptions,
    cb: Callback<NewTreasuryAddress>
  ): void;

  once(event: "NewTreasuryGuardian", cb: Callback<NewTreasuryGuardian>): void;
  once(
    event: "NewTreasuryGuardian",
    options: EventOptions,
    cb: Callback<NewTreasuryGuardian>
  ): void;

  once(event: "NewTreasuryPercent", cb: Callback<NewTreasuryPercent>): void;
  once(
    event: "NewTreasuryPercent",
    options: EventOptions,
    cb: Callback<NewTreasuryPercent>
  ): void;

  once(event: "RepayNAI", cb: Callback<RepayNAI>): void;
  once(event: "RepayNAI", options: EventOptions, cb: Callback<RepayNAI>): void;
}
